### ISSUE TITLE
Missing packagist.org package

### ISSUE THREAD

**Issue by MrsKensington** [umpirsky/locale-list#2]
Your other country, language and currency list packages are really useful, it would be great if we could have the locale list as a package on packagist.org as well.

**Comment by umpirsky** [comment]
It would be easy to create one. :+1: 

It just takes time. :)

**Comment by MrsKensington** [comment]
Is there anything I can do to help?

I created a fork and had a go at making a package (https://packagist.org/packages/mrs-kensington/locale-list). I had to do the following...

1. Changed composer.json so the required php version was ">=5.4"
2. Change the name to in composer.json to be one I can import (obviously you wont need to do that)
3. Create a release v1.0.0

Once I had done that I could create the package on packagist.org and then configure under github's settings the packagist integration to trigger an update when the repo changes.

**Comment by umpirsky** [comment]
Done https://packagist.org/packages/umpirsky/locale-list.

Thanks!
