### ISSUE TITLE
zh_HK , zh_MO , zh_TW is not correct

### ISSUE THREAD

**Issue by moxuanyuan** [umpirsky/locale-list#6]
Please follow the instructions below to transfer the contents

 zh_HK = zh_Hant_HK

zh_MO = zh_Hant_MO

zh_TW = zh_Hant_TW

**Comment by umpirsky** [comment]
Thanks, but this data is coming form [ICU database](http://site.icu-project.org/), so that's where you should report issues. This just converts it to other formats.
